"""Create screenshots table

Revision ID: 9763c38ae3b9
Revises: 
Create Date: 2025-04-24 16:34:21.848744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9763c38ae3b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='screenshot_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('screenshots_pkey'))
    )
    op.create_index(op.f('screenshots_status_idx'), 'screenshots', ['status'], unique=False)
    op.create_index(op.f('screenshots_url_idx'), 'screenshots', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('screenshots_url_idx'), table_name='screenshots')
    op.drop_index(op.f('screenshots_status_idx'), table_name='screenshots')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
